### ISSUE TITLE
Magic characters when decoding URLs

### ISSUE THREAD

**Issue by stephenafamo** [sethvargo/go-envconfig#10]
Not sure why, but URLs are not being decoded properly.

The url.URL type implements the BinaryUnmarshaler interface (https://golang.org/pkg/net/url/#URL.UnmarshalBinary)

However, when used in a config struct, the unmarshaling adds an `@` see this (https://play.golang.org/p/VrZDD85bR6j)

**Comment by sethvargo** [comment]
That's... interesting. The `@` symbol doesn't actually appear in any Go files, so this should be fun to debug...

**Comment by sethvargo** [comment]
Hmm okay, so the `@` is appearing because during marshal/unmarshal, "User" is being set to a value somehow...

```diff
              	Field: url.URL{
              		Scheme: "http",
              		Opaque: "",
            - 		User:   nil,
            + 		User:   s"",
              		Host:   "simple.test",
              		Path:   "/",
              		... // 4 identical fields
              	},
              }
```

**Comment by stephenafamo** [comment]
Works now. Great work.
