### ISSUE TITLE
Silently discards part of default value

### ISSUE THREAD

**Issue by vfaronov** [sethvargo/go-envconfig#34]
Given:
```
var cfg struct {
	Field1 string `env:"FIELD1,default=first"`
	Field2 string `env:"FIELD1,default=second to $FIELD1"`
}
os.Setenv("FIELD1", "one")
err := envconfig.Process(context.Background(), &cfg)
```
I would expect any of:
* `cfg.Field2 == "second to one"`
* `cfg.Field2 == "second to $FIELD1"`
* `err != nil`

Instead, I observe: `cfg.Field2 == "one"`

**Comment by sethvargo** [comment]
Hi @vfaronov 

I just [added a passing test for this](https://github.com/sethvargo/go-envconfig/commit/c5330fbea1cc22bc2d0b3089d46019931a1372d7). I think you have an error in your code:

```go
var cfg struct {
	Field1 string `env:"FIELD1,default=first"`
	Field2 string `env:"FIELD1,default=second to $FIELD1"`
        // ERROR:                ^
}
os.Setenv("FIELD1", "one")
err := envconfig.Process(context.Background(), &cfg)
```

I think you want the second `env` structure to read:

```
Field2 string `env:FIELD2,default=second to $FIELD1`
```

**Comment by vfaronov** [comment]
Oh dear... Thanks!
