### ISSUE TITLE
The best error available is not the one returned

### ISSUE THREAD

**Issue by maximerety** [sethvargo/go-envconfig#38]
Hi there,

I have a use case where a custom type (an enum) implements both the `envconfig.Decoder` and `json.Unmarshaler` interfaces (e.g. for use as a value in a JSON body in an HTTP call).

When an invalid value is provided, the `EnvDecode` method errors first, then the `UnmarshalJSON` errors too, and the last error returned by `UnmarshalJSON` is forwarded to the caller.

But that error is not human-friendly, because it's a generic JSON decoding failure, whereas the error I'm returning in `EnvDecode` would have been a better choice.

For reference, here's a bit of pseudo-code corresponding to the case described above:

* Optimal error returned by `EnvDecode`: https://play.golang.org/p/4sDh1tnevVu
* Suboptimal error, due to the addition of the `json.Unmarshaler` interface: https://play.golang.org/p/Z2GIhUNEMOs

I would advocate that when the developer explicitly chooses to implement the `envconfig.Decoder` interface, the internal `processAsDecoder` method should only try to use `EnvDecode` and not go through other decoders on error.

In that case, the `EnvDecode` method is the most adequate logic available to decode the value, and the error returned, if any, is the most useful we can get and should be preferably returned to the caller.

**Comment by sethvargo** [comment]
https://github.com/sethvargo/go-envconfig/pull/39
