### ISSUE TITLE
Consider moving the env var regex matching into the OsLookuper

### ISSUE THREAD

**Issue by johnpena** [sethvargo/go-envconfig#45]
The `Process` functions run each variable key through the `envvarNameRe` regex, and throws an error if the key doesn't match the regex. The validation of keys in such a way is really only a requirement if you're looking up a variable in the OS environment, e.g. using an `OsLookuper`. Currently, I can't set an arbitrary key to be used in my environment struct, e.g. something with dashes, even if I'm using an additional `Lookuper` where this type of validation might not be a requirement. Moving the regex matching into the `OsLookuper` would solve this problem and would be a more natural place for this kind of validation.

**Comment by johnpena** [comment]
Alternatively, consider removing this check entirely. It's not a strict requirement that environment variables be formatted as per the regex. The following program is valid and works just fine:

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	os.Setenv("this-is-a-test", "whatever")
	fmt.Println(os.Getenv("this-is-a-test"))
}
```

**Comment by sethvargo** [comment]
The requirement is derived from the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02), which states:

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

The primary purpose of this library is to map environment variables into struct values. The Lookuper abstraction exists [primarily for testing](https://github.com/sethvargo/go-envconfig#testing) and not as way to source non-environment variables at runtime. Similarly, moving the check into the `OsLookuper` creates significant behavior divergence with the `MapLookuper`, which could introduce subtle bugs where issues are only discovered at deployment time.

I don't think it makes sense to support values for environment keys that fall outside the spec of what POSIX supports.
