### ISSUE TITLE
Broken pointer initialization 

### ISSUE THREAD

**Issue by williamgcampbell** [sethvargo/go-envconfig#56]
In the [latest commit](https://github.com/sethvargo/go-envconfig/commit/e94cab64c1ca28aa3ec8f22d764d386f9905d5c7) there was a change to the way that the library initialized pointer structs by default. 

I've opened a PR with a proposed fix to the regression:
https://github.com/sethvargo/go-envconfig/pull/57

**Comment by sethvargo** [comment]
Thanks!
