### ISSUE TITLE
custom `Decoder` is not called on input struct, it is only called on fields within a struct

### ISSUE THREAD

**Issue by twmb** [sethvargo/go-envconfig#60]
If I pass a type that implements `Decoder` to `Process`, the `EnvDecode` function is not called. However, if a field _within_ my input struct implements `Decoder`, then `EnvDecode` is called.

In https://go.dev/play/p/wforR2YscKr, I would expect `CALLED` to be printed after both `1` and `2`. It is only printed after `2`.

**Comment by sethvargo** [comment]
Hi @twmb 

Thank you for opening an issue.  I'm not sure how this makes sense. The custom decoder accepts the environment variable as an input to the function. In your example, there's no place to define _which_ environment variable to pass to the custom decode function.

What problem are you trying to solve?

**Comment by sethvargo** [comment]
> I think I see what you mean: it's impossible to define a key for the top level input.

Right - you have to wrap it in another struct unfortunately. That's just a limitation of Go.

> What's odd is that EnvDecode is being called at all given there can be no key in the first example, and there is no key in the second example. This is an artifact of the investigation into https://github.com/sethvargo/go-envconfig/issues/61

Yea that makes sense. I'm going to close this out and we'll figure out a solution to #61.
