### ISSUE TITLE
unset env-vars does not play nicely with custom decode functions

### ISSUE THREAD

**Issue by twmb** [sethvargo/go-envconfig#61]
envconfig.go has this specific block of logic:

https://github.com/sethvargo/go-envconfig/blob/39c9bc7010cc446cf0fb569a3aedfa6b0de8462a/envconfig.go#L570-L581

I agree with the sentiment of the block logic: custom decoders may want to process empty env vars in a specific way, rather than return early.

However, if an env for is not set at all, it is currently loaded as an empty string (here: https://github.com/sethvargo/go-envconfig/blob/39c9bc7010cc446cf0fb569a3aedfa6b0de8462a/envconfig.go#L468-L491)

It seems as if env var overrides should _not_ be applied if the env var does not exist. In my code, this is conflict with a type that uses a field like so,

```go
type SomeType struct {
    // ..other fields

    LogLevel zapcore.Level `env:"LEVEL,omitempty"`
}
```
I specifically define in my config file that the level is debug. The zapcore code handles empty input to `UnmarshalText` as ok and writes the log level to info (see here: https://github.com/uber-go/zap/blob/6f34060764b5ea1367eecda380ba8a9a0de3f0e6/zapcore/level.go#L142-L143), and I have no control to stop this override.

My only current option is to wrap this type in another type that specifically handles the empty string as a no-op. Unfortunately, this breaks the potentially _desired_ behavior of when an empty string is _actually_ specified changing the level to info.

ISTM that the better default would be to not process env vars if the env var does not exist.

**Comment by sethvargo** [comment]
> The zapcore code handles empty input to UnmarshalText as ok and writes the log level to info (see here: https://github.com/uber-go/zap/blob/6f34060764b5ea1367eecda380ba8a9a0de3f0e6/zapcore/level.go#L142-L143), and I have no control to stop this override.

I don't understand. Why can't you just set a default envconfig value to another value?

```go
type SomeType struct {
    // ..other fields

    LogLevel zapcore.Level `env:"LEVEL,omitempty,default=debug"`
}
```

I'm also not sure what you mean by "env var overrides".

**Comment by twmb** [comment]
https://go.dev/play/p/amK4b3kwJ97

Envconfig is overriding a field that was loaded from a file, even though the environment variable is not set.

Using default doesn't work because then envconfig overrides with the default value, and the config file has a different value than the default.

**Comment by twmb** [comment]
For an example using zapcore, https://go.dev/play/p/Ug1VlORuxjS
