### ISSUE TITLE
Is there a possibility to use it with map[string][]string

### ISSUE THREAD

**Issue by franpog859** [sethvargo/go-envconfig#63]
I have a quick question. Is there a possibility to use it with `map[string][]string` type? I didn't find it in the description or the tests but maybe there is possible

**Comment by sethvargo** [comment]
Hi @franpog859 

Thank you for opening an issue. What is the use case - could you provide an example?

**Comment by sethvargo** [comment]
I think the challenge is then representing multiple values. The `separator` key applies to both the map and string values, so there's no two-dimensional way to represent this three-dimensional object.

You could build your own decoder type (untest):

```go
type HTTPHeaderDecoder http.Header

func (d *HTTPHeaderDecoder) EnvDecode(in string) error {
  result := make(map[string][]string)

  // parse the input string into your 3d structure
  for k, v := range parsed {
    result.Add(k, v)
  }

  *d = result
}
```

To make this work, I think you'd actually need to provide duplicate map keys:

```go
type TestConfig struct {
  ExpectedHeaders map[string][]string `env:"EXPECTED_HEADERS,default='a:b;c:d;c:e'"`
}
```

**Comment by franpog859** [comment]
Yeah, I also thought about some custom decoder. I was just wondering if there is a possibility to do it without it :D Anyway, thanks for a quick response! I think I'll just close this issue in this case
