### ISSUE TITLE
Import path seems to be ambiguous

### ISSUE THREAD

**Issue by mwf** [sethvargo/go-envconfig#7]
Hi!

`import "github.com/sethvargo/go-envconfig/pkg/envconfig"`

Such import contains almost duplicated parts - `go-envconfig` and `envconfig` at the end.
Have you thought about moving go code to the project root? 

We will have more elegant and meaningful import path then.

**Comment by sethvargo** [comment]
Hey @mwf 

Some folks brought this up on Twitter. I'm happy to move it, but I think that will break existing imports.

**Comment by mikehelmick** [comment]
I think it's fine to do as long we assign a long lived version to the way it currently is (`0.1`?)

**Comment by sethvargo** [comment]
Done

**Comment by mwf** [comment]
Thanks!

It's great you decided to fix the import path :)
0.1 version is indeed young enough for such changes.
