### ISSUE TITLE
Overwrite and default logic does not work with bool pointer 

### ISSUE THREAD

**Issue by capri-xiyue** [sethvargo/go-envconfig#71]
```
{
			name: "bool_pointer_overwrite_default",
			input: &struct {
				Field *bool `env:"FIELD,noinit,overwrite,default=true"`
			}{
				Field: new(bool),
			},
			exp: &struct {
				Field *bool `env:"FIELD,noinit,overwrite,default=true"`
			}{
				Field: new(bool),
			},
			lookuper: MapLookuper(nil),
		},
```
I wrote test cases as above and it failed.
It does not follow the logic listed in https://github.com/sethvargo/go-envconfig#overwrite
`If the struct field has a non-zero value and a default is set and if no environment variable is specified, the struct field's existing value will be used (the default is ignored).`

**Comment by sethvargo** [comment]
Fixed in https://github.com/sethvargo/go-envconfig/pull/73
