### ISSUE TITLE
Why do you use regex to validate env var name?

### ISSUE THREAD

**Issue by renanbastos93** [sethvargo/go-envconfig#72]
I saw this line [98](https://github.com/sethvargo/go-envconfig/blob/63e4089fe1a599af605c681f25b5c34b3252514c/envconfig.go#L98) but I believe that be unnecessary to use regex it is 3 times slower compared to `\w+` is the same result. Case I'm wrong, please fix me. Maybe you can use Unicode to validate strings and gain performance to reduce processing.

https://github.com/sethvargo/go-envconfig/blob/63e4089fe1a599af605c681f25b5c34b3252514c/envconfig.go#L98

**Comment by sethvargo** [comment]
Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and **do not begin with a digit**. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.

You can see this in your shell, try:

```
export 1=2
```

What is the use case where this performance overhead is actually significant? Can you share where you got these benchmarks?

**Comment by renanbastos93** [comment]
using regex:
BenchmarkEnvvarNameRe-8          9875601               121.2 ns/op             3 B/op          1 allocs/op

not use regex:
BenchmarkValidateEnv-8          145751532                8.179 ns/op           0 B/op          0 allocs/op

See my code:
https://github.com/sethvargo/go-envconfig/compare/main...renanbastos93:go-envconfig:propose/validate-env-var-without-regex?expand=1

What do you think ?

**Comment by sethvargo** [comment]
Okay I'm not opposed to this change. I'd like like to understand the use case where ~100ns is impactful or noticable though. Do you want to submit a PR?

**Comment by sethvargo** [comment]
Also, the alloc is coming from `[]byte`, not the regex. If you make `"ABC"` a const and use MatchString, it's a little better.

**Comment by renanbastos93** [comment]
Awesome, I saw your change based on my commitment. Congrats. Thanks for listening to me. 

see ya
