### ISSUE TITLE
Custom envvar validators

### ISSUE THREAD

**Issue by NeonWizard** [sethvargo/go-envconfig#75]
Is there any way to define a custom validator for an environment variable? Such as a custom regex test?

**Comment by sethvargo** [comment]
Hi @NeonWizard

envconfig isn't intended to be a validation library. That being said, you could use a [mutator](https://github.com/sethvargo/go-envconfig#extension) to achieve this behavior. Something like:

```go
func resolveSecretFunc(ctx context.Context, key, value string) (string, error) {
  if re.Match(val) {
    return "", fmt.Errorf("invalid format for %q", key)
  }
  return value, nil
}

```
