### ISSUE TITLE
Feat: make environment variables discoverable

### ISSUE THREAD

**Issue by zbindenren** [sethvargo/go-envconfig#77]
Currently it is not possible to find out how someone can configure an application via environment variables without checking the source code or manually creating a help or usage (which is error prone).

It would be great if we had something like:

```go
type MyConfig struct {
  Port     int    `env:"PORT" usage:"The server port."`
  Username string `env:"USERNAME" usage:"The login username."`
}
```

and maybe a function like:

```go
func Usage(w io.Writer) {
}
```

that would print a usage like with variable names and type and default values. This could also be printed out, when a required field is missing.

What do you think? Good idea, bad idea?

**Comment by sethvargo** [comment]
Hi @zbindenren 

Thank you for opening an issue. I'm not sure I how I see this being used. Could you give an example?

**Comment by zbindenren** [comment]
Hi @sethvargo 

Thanks for the quick response. Sometimes I wonder if I am the only one that wants this feature :rofl: . 

I found this feature only in [this](https://github.com/junk1tm/env#usage-on-error) env package. It displays a usage when a required environment variable is missing. I am not using that package because it doesn't support structs in structs.

I could document the environment variables for a service in the README, but I think this is error prone and doesn't scale well. 

With this feature I could do the following:

```go
package main

import (
    "flag"
    "log"
    "os"

    "github.com/sethvargo/go-envconfig"
)

func main() {
    cfg := struct {
        Host string `env:"HOST"  desc:"The host"`
        Port int    `env:"PORT" desc:"The port"`
    }{}

    flag.Usage = func() {
        envconfig.Usage(os.Stderr, cfg)
    }

    flag.Parse()
}
```

Which would print something like:

```console
$ cmd -h
Usage:
  HOST  string  default localhost  The host
  PORT  int     default 0          The port
```

Then I know what variables are required, the default values, the type and description.

Or when the starting of the service (or command) fails because of a missing variable or wrong type, this message could be shown.

**Comment by sethvargo** [comment]
Hi @zbindenren 

I think users would want to customize that output heavily, so we'd end up returning some kind of structure that you iterate over. But in reality, I think it's more common to do this kind of validation and output manually.

If you're looking for something that's more high-level, I'd check out viper and cobra.
