### ISSUE TITLE
Feat: conditionally required 

### ISSUE THREAD

**Issue by stampy88** [sethvargo/go-envconfig#81]
Hi, one of the things I generally do is have different settings required only if the feature flag is enabled. So for example:
```
type AppConfig struct {
	Port        int         `env:"PORT"`
	KafkaConfig KafkaConfig `env:",prefix=KAFKA_"`
}

type KafkaConfig struct {
	Enabled bool     `env:"ENABLED,required,enabler"`
	Brokers []string `env:"BROKERS,required"`
}
```
The `enabler` option would be used to designate a single `bool` on a struct which would be used to enable/disable the "required-ness" of the rest of the `required` fields on the struct. So in the example above, only if `KAKFA_ENABLED == true`, would `go-envconfig` require `KAFKA_BROKERS` to be set. 

Thoughts?

**Comment by sethvargo** [comment]
Hi @stampy88 

Thank you for opening an issue. This would be _very_ complex to implement, since we'd have to walk the struct fields twice to find an enabler field, then re-process the struct based on the findings (if any).

The "required" validation is intentionally dumb and provides minimal validation. It's not meant to be a replacement for a validation library. For complex validations, I would check out https://github.com/go-playground/validator.

**Comment by stampy88** [comment]
Hi @sethvargo, I didn't think what I was proposing was complex validation (I do realize it would be two passes). The library already gives the idea of an environment variable being required. This is just a slight variation of that. If another library is brought in to do more complex validation, the error messages would be completely different, i.e. they would not tell you are not setting an environment variable, but rather some struct validation message, e.g. 
```
type topLevel struct {
	Field1      string `validate:"required"`
	InnerConfig inner  `validate:"required"`
}

type inner struct {
	Enabled bool
	Field1  string `validate:"required_if=Enabled true"`
	Field2  string `validate:"required_if=Enabled true"`
}

func TestValidate(t *testing.T) {
	v := validator.New()
	err := v.Struct(topLevel{
		InnerConfig: inner{
			Enabled: true,
		},
	})
	require.NoError(t, err)
}
```

```
Error:      	Received unexpected error:
        	            	Key: 'topLevel.Field1' Error:Field validation for 'Field1' failed on the 'required' tag
        	            	Key: 'topLevel.InnerConfig.Field1' Error:Field validation for 'Field1' failed on the 'required_if' tag
        	            	Key: 'topLevel.InnerConfig.Field2' Error:Field validation for 'Field2' failed on the 'required_if' tag

**Comment by sethvargo** [comment]
The idea that go-envconfig marks environment variables as required was a design mistake in the first place. It really should only be responsible for loading things into structs; subsequent libraries or custom logic should be responsible for doing validation.
