### ISSUE TITLE
noinit doesn't know about nil slices

### ISSUE THREAD

**Issue by kluzzebass** [sethvargo/go-envconfig#82]
I tried to use `noinit` with a `[]byte` slice, but the parser complained that `field must be a pointer to have noinit`. It seems a bit unnecessary to insist on having a pointer to a slice, since a slice in itself can be `nil`. Consider the following code:

```
package main

import "fmt"

type Lala struct {
	Blah []byte
}

func main() {
	lala := Lala{}
	if lala.Blah == nil {
		fmt.Println("Blah is nil")
	}
	lala.Blah = []byte{}
	if lala.Blah != nil {
		fmt.Println("Blah is not nil")
	}
}
```

The result is:
```
Blah is nil
Blah is not nil
```

**Comment by sethvargo** [comment]
https://github.com/sethvargo/go-envconfig/pull/83

Note this isn't possible with Arrays, because Arrays _must_ be allocated (enforced by the compiler).
