### ISSUE TITLE
how to use with nested structs

### ISSUE THREAD

**Issue by bsdlp** [sethvargo/go-envconfig#87]
hey - i have a use case for `map[string]struct` but the struct section in the documentation is lacking examples!

https://github.com/sethvargo/go-envconfig#structs

**Comment by sethvargo** [comment]
Can you please provide an example?

**Comment by sethvargo** [comment]
Hi there - I'm going to close this due to a lack of reply. If this is still a change you would like to see, please open a new issue. Thanks!
