### ISSUE TITLE
Add parsing of days, months, etc. type properties for time.Duration

### ISSUE THREAD

**Issue by labi-le** [sethvargo/go-envconfig#90]
```golang
type Config struct {
	UserStatusTTL           time.Duration `env:"USER_STATUS_TTL,default=7d"`
}
```

**Comment by mikehelmick** [comment]
The parsing is based off the built in time.Duration type and what it is able to parse.
https://pkg.go.dev/time#ParseDuration

It doesn't support granularity of days or months.

Months isn't a fixed concept anyway, so it would impossible to say what a "month" actually represents.

Typically people will use multiples of hours to indicate what you want to actually represent.

**Comment by sethvargo** [comment]
Related: https://github.com/golang/go/issues/11473
